name: Main

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions: { contents: read, pull-requests: write }

    steps:
      - uses: actions/checkout@v6

      - uses: ./actions/init-bun

      - uses: raven-actions/actionlint@v2

      - run: bun run test-coverage

      - uses: ./actions/coverage-report
        with:
          coverage-url: https://git-lfs-hub.github.io/ci-cd
