name: CD

on:
  workflow_call:

env:
  GLH_VARS_JSON: ${{ vars.GLH_VARS_JSON || secrets.GLH_VARS_JSON }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM || secrets.TURBO_TEAM }}
  TURBO_TEAMID: ${{ vars.TURBO_TEAMID || secrets.TURBO_TEAMID }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Init
        uses: ./ci-cd/actions/init

      - name: CD
        uses: ./ci-cd/actions/cd
        with:
          cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Turbo Summary
        uses: ./ci-cd/actions/turbo-summary
