name: E2E

on:
  workflow_call:

env:
  GLH_VARS_JSON: ${{ vars.GLH_VARS_JSON || secrets.GLH_VARS_JSON }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM || secrets.TURBO_TEAM }}
  TURBO_TEAMID: ${{ vars.TURBO_TEAMID || secrets.TURBO_TEAMID }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

permissions:
  contents: write

jobs:
  e2e:
    name: E2E
    runs-on: ubuntu-latest
    concurrency:
      group: lfs-server-prod-e2e
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Init
        uses: git-lfs-hub/ci-cd/actions/init@main

      - name: Test
        uses: git-lfs-hub/ci-cd/actions/e2e-test@main
        with:
          gh-pat: ${{ secrets.GLH_STAGING_GITHUB_PAT }}
          login-secret: ${{ secrets.GLH_LOGIN_SECRET }}
          pr-number: main
