name: Staging

on:
  workflow_call:

env:
  GLH_VARS_JSON: ${{ vars.GLH_VARS_JSON || secrets.GLH_VARS_JSON }}
  TURBO_REMOTE_CACHE_SIGNATURE_KEY: staging

permissions:
  contents: write

jobs:
  staging:
    name: CD + E2E
    runs-on: ubuntu-latest
    concurrency:
      group: lfs-server-staging-e2e
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v6
        with:
          repository: ${{ github.repository }}
          submodules: recursive
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Init Staging
        uses: git-lfs-hub/ci-cd/actions/init-staging@main

      - name: Deploy Staging
        uses: git-lfs-hub/ci-cd/actions/cd@main
        with:
          cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Run E2E Tests
        uses: git-lfs-hub/ci-cd/actions/e2e-test@main
        with:
          gh-pat: ${{ secrets.GLH_STAGING_GITHUB_PAT }}
          login-secret: ${{ secrets.GLH_STAGING_LOGIN_SECRET }}
          pr-number: ${{ github.event.pull_request.number }}
