name: Staging

on:
  workflow_call:
    inputs:
      test-repo:
        description: "owner/repo used by e2e tests"
        type: string
        required: false
    secrets:
      CLOUDFLARE_API_TOKEN: { required: true }
      GLH_STAGING_GITHUB_PAT: { required: false }
      GLH_STAGING_LOGIN_SECRET: { required: false }

env:
  GLH_ENV: staging
  GLH_VARS_JSON: ${{ vars.GLH_VARS_JSON }}
  TURBO_REMOTE_CACHE_SIGNATURE_KEY: staging

permissions:
  contents: write

jobs:
  staging:
    name: CD + E2E
    runs-on: ubuntu-latest
    concurrency:
      group: lfs-server-staging-e2e
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v6
        with:
          repository: ${{ github.repository }}
          submodules: recursive
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Init Staging
        uses: git-lfs-hub/ci-cd/actions/init-deploy@main
        with:
          env: staging

      - name: Deploy Staging
        uses: git-lfs-hub/ci-cd/actions/deploy@main
        with:
          cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Run E2E Tests
        if: ${{ inputs.test-repo != '' }}
        uses: git-lfs-hub/ci-cd/actions/e2e-test@main
        with:
          gh-pat: ${{ secrets.GLH_STAGING_GITHUB_PAT }}
          login-secret: ${{ secrets.GLH_STAGING_LOGIN_SECRET }}
          pr-number: ${{ github.event.pull_request.number }}
          test-repo: ${{ inputs.test-repo }}
